name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer checkout do código
      - name: Check out the repository
        uses: actions/checkout@v3
      # Passo 2: Instalar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Passo 3: Instalar dependências do projeto
      - name: Install dependencies
        run: npm install
      # Passo 4: Rodar os testes unitários
      - name: Run tests
        run: npm test
